name: dvc-cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 
          git fetch --prune ## https://git-scm.com/docs/git-fetch
          dvc metrics diff --show-md python-dvc-metric > report.md
          echo "## Validating results by region" >> report.md
          echo "![](./by_region.png)" >> report.md
          cml comment create report.md
